### ISSUE TITLE
Initialization exception

### ISSUE THREAD

**Issue by VladislavAntonyuk** [sarxos/win-registry#4]
windowsRegistry = com.github.sarxos.winreg.WindowsRegistry@396fb9ed

2019-01-21 08:25:21.482 [AWT-EventQueue-0] ERROR Exception occurred:
java.lang.ExceptionInInitializerError: null
	at com.github.sarxos.winreg.WindowsRegistry.readString(WindowsRegistry.java:61) ~[ui-1.0-jar-with-dependencies.jar:?]
	at com.github.sarxos.winreg.WindowsRegistry.readString(WindowsRegistry.java:46) ~[ui-1.0-jar-with-dependencies.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue.access$600(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at com.github.sarxos.winreg.internal.ReflectedMethods.setupMethod(ReflectedMethods.java:49) ~[ui-1.0-jar-with-dependencies.jar:?]
	at com.github.sarxos.winreg.internal.ReflectedMethods.<clinit>(ReflectedMethods.java:31) ~[ui-1.0-jar-with-dependencies.jar:?]
	... 18 more
Caused by: java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int, [B, int)
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
	at com.github.sarxos.winreg.internal.ReflectedMethods.setupMethod(ReflectedMethods.java:47) ~[ui-1.0-jar-with-dependencies.jar:?]
	at com.github.sarxos.winreg.internal.ReflectedMethods.<clinit>(ReflectedMethods.java:31) ~[ui-1.0-jar-with-dependencies.jar:?]
	... 18 more

**Comment by pban** [comment]
The library is attempting to call some private class / methods via reflection, in your case:
NoSuchMethodException: java.util.prefs.WindowsPreferences.**WindowsRegOpenKey**(int, [B, int)
However the WindowsRegOpenKey method no longer accepts the parameters (int, byte[], int), but (long, byte[], int). To fix this:
1. I changed the defined parameters in class ReflectedMethods of this library to accept long values.
2. Modified the ReflectedMethods.invoke method to accept Long values in the if-else block around line 140.
3. Then you might get some cast exceptions for example in the ReflectedMethods.keyOpen method when it is attempting to case a long[] to int[], so you have to fix this also.

**Comment by VladislavAntonyuk** [comment]
the first parameter is HKey, which is int. Probably you should change it too

**Comment by VladislavAntonyuk** [comment]
I just made call windowsRegistry.readString(HKey.HKCU, string, string).
what should I change?

**Comment by VladislavAntonyuk** [comment]
Also, the latest version in Maven was uploaded in 2014, but the latest commit was in 2016.

**Comment by sarxos** [comment]
If this is the case described by @pban this will need a fix in library. What Java version are you using?

**Comment by VladislavAntonyuk** [comment]
11

**Comment by SmigloRekter** [comment]
fajne

**Comment by mgonzalezg9** [comment]
I am getting the same problem. Please @pban update the library so that the error fixes and this issue gets closed.

**Comment by BullyWiiPlaza** [comment]
Same problem...
a new and fixed release would be highly appreciated.

**Comment by polybas** [comment]
If you use java version 8 and later all WindowsPreferences declaredMethods start with int.
If you use java version > 8 like 9, 11, 15 all WindowsPreferences declaredMethods start with long.
It edit in java/util/prefs/WindowsPreferences
